version: '3.9'

services:
  web:
    build: .
    container_name: farmer_app_backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/farmer_db
    depends_on:
      - db
    volumes:
      - .:/app
    restart: always

  db:
    image: postgres:14
    container_name: farmer_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: farmer_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
