version: '3.9'

services:
  web:
    build: .
    container_name: farmer_web
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/farmer_db
    depends_on:
      - db
    volumes:
      - type: bind
        source: .
        target: /app
    networks:
      - backend

  db:
    image: postgres:14
    container_name: farmer_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: farmer_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
    networks:
      - backend

  nginx:
    image: nginx:latest
    container_name: farmer_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - web
    restart: always
    networks:
      - backend

volumes:
  pgdata:

networks:
  backend:
    external: false
